name: Testing

on:
  push:
    branches:
      - main
    paths:
      - "criminalip/**.py"

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pipenv'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      
      - name: Run test suite
        run: |
          pipenv run pytest
        env:
          API_KEY: ${{ secrets.API_KEY }}